Actualizar botssh

diff --git a/Modulos/botssh b/Modulos/botssh
--- a/Modulos/botssh
+++ b/Modulos/botssh
@@ -17,34 +17,34 @@ fun_bar() {
         touch $HOME/fim
     ) >/dev/null 2>&1 &
     tput civis
-    echo -ne "\033[1;33m["
+    echo -ne "["
     while true; do
         for ((i = 0; i < 18; i++)); do
-            echo -ne "\033[1;31m#"
+            echo -ne "#"
             sleep 0.1s
         done
         [[ -e $HOME/fim ]] && rm $HOME/fim && break
-        echo -e "\033[1;33m]"
+        echo -e "]"
         sleep 1s
         tput cuu1
         tput dl1
-        echo -ne "\033[1;33m["
+        echo -ne "["
     done
-    echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
+    echo -e "] - OK !"
     tput cnorm
 }
 
 fun_botOnOff() {
     [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) = '0' ]] && {
         clear
-        echo -e "\E[44;1;37m             INSTALADOR BOT SSHPLUS                \E[0m\n"
-        echo -ne "\033[1;32mINFORME SU TOKEN de bot:\033[1;37m "
+        echo "             INSTALADOR BOT SSHPLUS                "
+        echo -ne "INFORME SU TOKEN de bot: "
         read tokenbot
         echo ""
-        echo -ne "\033[1;32mINFORME TU ID de telegram:\033[1;37m "
+        echo -ne "INFORME TU ID de telegram: "
         read iduser
         clear
-        echo -e "\033[1;32mINICIANDO BOT SSHPLUS \033[0m\n"
+        echo "INICIANDO BOT SSHPLUS "
         fun_bot1() {
         	[[ "$(grep -wc '16' /etc/issue.net)" != '0' ]] && {
         		wget -qO- sshplus.xyz/script/ShellBot.sh > /etc/SSHPlus/ShellBot.sh
@@ -67,12 +67,12 @@ fun_botOnOff() {
             cd $HOME
         }
         fun_bar 'fun_bot1'
-        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m BOT SSHPLUS ACTIVADO !\033[0m" || echo -e "\n\033[1;31m ERROR! REANALISE SUS INFORMACIONES\033[0m"
+        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n BOT SSHPLUS ACTIVADO !" || echo -e "\n ERROR! REANALISE SUS INFORMACIONES"
         sleep 2
         menu
     } || {
         clear
-        echo -e "\033[1;32mPARANDO BOT SSHPLUS... \033[0m\n"
+        echo "PARANDO BOT SSHPLUS... "
         fun_bot2() {
             screen -r -S "bot_plus" -X quit
             screen -wipe 1>/dev/null 2>/dev/null
@@ -83,25 +83,25 @@ fun_botOnOff() {
             sleep 1
         }
         fun_bar 'fun_bot2'
-        echo -e "\n\033[1;32m \033[1;31mBOT SSHPLUS PARADO! \033[0m"
+        echo -e "\n BOT SSHPLUS PARADO! "
         sleep 2
         menu
     }
 }
 
 fun_instbot() {
-    echo -e "\E[44;1;37m             INSTALADOR BOT SSHPLUS                \E[0m\n"
-    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATENCION \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
-    echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mEN SU TELEGRAM  BAYA A LOS SEGUINTE BOT\033[1;37m:\033[0m"
-    echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCREE  SU BOT \033[1;31mOPCION: \033[1;37m/newbot\033[0m"
-    echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@SSHPLUS_BOT \033[1;33mE PEGUE SU ID \033[1;31mOPCION: \033[1;37m/id\033[0m"
-    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[1;32m"
+    echo "             INSTALADOR BOT SSHPLUS                "
+    echo -e "                 [ ! ] ATENCION [ ! ]"
+    echo -e "\n1° - EN SU TELEGRAM  BAYA A LOS SEGUINTE BOT:"
+    echo -e "\n2° - BOT @BotFather CREE  SU BOT OPCION: /newbot"
+    echo -e "\n3° - BOT @SSHPLUS_BOT E PEGUE SU ID OPCION: /id"
+    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
     echo ""
     read -p "DESEA CONTINUAR ? [s/n]: " -e -i s resposta
     [[ "$resposta" = 's' ]] && {
         fun_botOnOff
     } || {
-        echo -e "\n\033[1;31mRetornando...\033[0m"
+        echo -e "\nRetornando..."
         sleep 2
         menu
     }
